<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/header.php');
$APPLICATION->SetTitle("Главная");
?>
	<div class="container">
		<div class="row">
			<?$APPLICATION->IncludeComponent(
				"bitrix:catalog",
				"catalog",
				array(
					"ACTION_VARIABLE" => "action",
					"ADD_ELEMENT_CHAIN" => "N",
					"ADD_PICT_PROP" => "-",
					"ADD_PROPERTIES_TO_BASKET" => "Y",
					"ADD_SECTIONS_CHAIN" => "Y",
					"AJAX_MODE" => "N",
					"AJAX_OPTION_ADDITIONAL" => "",
					"AJAX_OPTION_HISTORY" => "N",
					"AJAX_OPTION_JUMP" => "N",
					"AJAX_OPTION_STYLE" => "Y",
					"BASKET_URL" => "l/basket.php",
					"BIG_DATA_RCM_TYPE" => "personal",
					"CACHE_FILTER" => "N",
					"CACHE_GROUPS" => "N",
					"CACHE_TIME" => "36000000",
					"CACHE_TYPE" => "N",
					"COMMON_ADD_TO_BASKET_ACTION" => "ADD",
					"COMMON_SHOW_CLOSE_POPUP" => "N",
					"COMPATIBLE_MODE" => "Y",
					"COMPONENT_TEMPLATE" => "catalog",
					"CONVERT_CURRENCY" => "N",
					"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
					"DETAIL_ADD_TO_BASKET_ACTION" => array(
						0 => "BUY",
					),
					"DETAIL_ADD_TO_BASKET_ACTION_PRIMARY" => array(
						0 => "BUY",
					),
					"DETAIL_BACKGROUND_IMAGE" => "-",
					"DETAIL_BLOG_USE" => "N",
					"DETAIL_BRAND_USE" => "N",
					"DETAIL_BROWSER_TITLE" => "ATT_BRAND",
					"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
					"DETAIL_DETAIL_PICTURE_MODE" => "MAGNIFIER",
					"DETAIL_DISPLAY_NAME" => "Y",
					"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
					"DETAIL_FB_USE" => "N",
					"DETAIL_IMAGE_RESOLUTION" => "16by9",
					"DETAIL_MAIN_BLOCK_PROPERTY_CODE" => array(
						0 => "ATT_PRICE",
					),
					"DETAIL_META_DESCRIPTION" => "-",
					"DETAIL_META_KEYWORDS" => "-",
					"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
					"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
					"DETAIL_PROPERTY_CODE" => array(
						0 => "ATT_BRAND",
						1 => "ATT_DIAGONAL",
						2 => "ATT_RAM",
						3 => "ATT_PARTNER",
						4 => "ATT_PROCESSOR",
						5 => "ATT_PRICE",
						6 => "",
					),
					"DETAIL_SET_CANONICAL_URL" => "N",
					"DETAIL_SET_VIEWED_IN_COMPONENT" => "N",
					"DETAIL_SHOW_BASIS_PRICE" => "Y",
					"DETAIL_SHOW_MAX_QUANTITY" => "N",
					"DETAIL_SHOW_POPULAR" => "Y",
					"DETAIL_SHOW_SLIDER" => "N",
					"DETAIL_SHOW_VIEWED" => "Y",
					"DETAIL_STRICT_SECTION_CHECK" => "N",
					"DETAIL_USE_COMMENTS" => "N",
					"DETAIL_USE_VOTE_RATING" => "Y",
					"DETAIL_VK_USE" => "N",
					"DETAIL_VOTE_DISPLAY_AS_RATING" => "rating",
					"DISABLE_INIT_JS_IN_COMPONENT" => "N",
					"DISPLAY_BOTTOM_PAGER" => "Y",
					"DISPLAY_TOP_PAGER" => "Y",
					"ELEMENT_SORT_FIELD" => "sort",
					"ELEMENT_SORT_FIELD2" => "id",
					"ELEMENT_SORT_ORDER" => "asc",
					"ELEMENT_SORT_ORDER2" => "desc",
					"FILE_404" => "",
					"FILTER_HIDE_ON_MOBILE" => "N",
					"FILTER_VIEW_MODE" => "HORIZONTAL",
					"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
					"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
					"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "4",
					"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
					"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
					"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
					"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "4",
					"GIFTS_MESS_BTN_BUY" => "Выбрать",
					"GIFTS_SECTION_LIST_BLOCK_TITLE" => "Подарки к товарам этого раздела",
					"GIFTS_SECTION_LIST_HIDE_BLOCK_TITLE" => "N",
					"GIFTS_SECTION_LIST_PAGE_ELEMENT_COUNT" => "4",
					"GIFTS_SECTION_LIST_TEXT_LABEL_GIFT" => "Подарок",
					"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
					"GIFTS_SHOW_IMAGE" => "Y",
					"GIFTS_SHOW_NAME" => "Y",
					"GIFTS_SHOW_OLD_PRICE" => "Y",
					"HIDE_NOT_AVAILABLE" => "N",
					"HIDE_NOT_AVAILABLE_OFFERS" => "N",
					"IBLOCK_ID" => "2",
					"IBLOCK_TYPE" => "production",
					"INCLUDE_SUBSECTIONS" => "Y",
					"INSTANT_RELOAD" => "N",
					"LABEL_PROP" => "-",
					"LABEL_PROP_MOBILE" => "",
					"LABEL_PROP_POSITION" => "top-left",
					"LAZY_LOAD" => "N",
					"LINE_ELEMENT_COUNT" => "1",
					"LINK_ELEMENTS_URL" => "#SECTION_CODE#/#ELEMENT_CODE#/",
					"LINK_IBLOCK_ID" => "2",
					"LINK_IBLOCK_TYPE" => "production",
					"LINK_PROPERTY_SID" => "ATT_PARTNER",
					"LIST_BROWSER_TITLE" => "NAME",
					"LIST_ENLARGE_PRODUCT" => "STRICT",
					"LIST_ENLARGE_PROP" => "-",
					"LIST_META_DESCRIPTION" => "-",
					"LIST_META_KEYWORDS" => "-",
					"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
					"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false}]",
					"LIST_PROPERTY_CODE" => array(
						0 => "",
						1 => "",
					),
					"LIST_PROPERTY_CODE_MOBILE" => "",
					"LIST_SHOW_SLIDER" => "N",
					"LIST_SLIDER_INTERVAL" => "3000",
					"LIST_SLIDER_PROGRESS" => "N",
					"LOAD_ON_SCROLL" => "N",
					"MESSAGE_404" => "",
					"MESS_BTN_ADD_TO_BASKET" => "В корзину",
					"MESS_BTN_BUY" => "Купить",
					"MESS_BTN_COMPARE" => "Сравнение",
					"MESS_BTN_DETAIL" => "Подробнее",
					"MESS_BTN_SUBSCRIBE" => "Подписаться",
					"MESS_COMMENTS_TAB" => "Комментарии",
					"MESS_DESCRIPTION_TAB" => "Описание",
					"MESS_NOT_AVAILABLE" => "Нет в наличии",
					"MESS_PRICE_RANGES_TITLE" => "Цены",
					"MESS_PROPERTIES_TAB" => "Характеристики",
					"PAGER_BASE_LINK_ENABLE" => "N",
					"PAGER_DESC_NUMBERING" => "Y",
					"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
					"PAGER_SHOW_ALL" => "Y",
					"PAGER_SHOW_ALWAYS" => "Y",
					"PAGER_TEMPLATE" => "modern",
					"PAGER_TITLE" => "Товары",
					"PAGE_ELEMENT_COUNT" => "3",
					"PARTIAL_PRODUCT_PROPERTIES" => "N",
					"PRICE_CODE" => array(
						0 => "priceType",
					),
					"PRICE_VAT_INCLUDE" => "Y",
					"PRICE_VAT_SHOW_VALUE" => "N",
					"PRODUCT_ID_VARIABLE" => "id",
					"PRODUCT_PROPERTIES" => array(
						0 => "ATT_PARTNER",
					),
					"PRODUCT_PROPS_VARIABLE" => "prop",
					"PRODUCT_QUANTITY_VARIABLE" => "quantity",
					"PRODUCT_SUBSCRIPTION" => "Y",
					"SEARCH_CHECK_DATES" => "Y",
					"SEARCH_NO_WORD_LOGIC" => "Y",
					"SEARCH_PAGE_RESULT_COUNT" => "50",
					"SEARCH_RESTART" => "N",
					"SEARCH_USE_LANGUAGE_GUESS" => "Y",
					"SECTIONS_HIDE_SECTION_NAME" => "N",
					"SECTIONS_SHOW_PARENT_NAME" => "Y",
					"SECTIONS_VIEW_MODE" => "LINE",
					"SECTION_ADD_TO_BASKET_ACTION" => "ADD",
					"SECTION_BACKGROUND_IMAGE" => "-",
					"SECTION_COUNT_ELEMENTS" => "Y",
					"SECTION_ID_VARIABLE" => "SECTION_ID",
					"SECTION_TOP_DEPTH" => "1",
					"SEF_FOLDER" => "/",
					"SEF_MODE" => "Y",
					"SET_LAST_MODIFIED" => "N",
					"SET_STATUS_404" => "Y",
					"SET_TITLE" => "Y",
					"SHOW_404" => "Y",
					"SHOW_DEACTIVATED" => "Y",
					"SHOW_DISCOUNT_PERCENT" => "N",
					"SHOW_MAX_QUANTITY" => "N",
					"SHOW_OLD_PRICE" => "N",
					"SHOW_PRICE_COUNT" => "1",
					"SHOW_TOP_ELEMENTS" => "Y",
					"SIDEBAR_DETAIL_SHOW" => "N",
					"SIDEBAR_PATH" => "",
					"SIDEBAR_SECTION_SHOW" => "Y",
					"TEMPLATE_THEME" => "black",
					"TOP_ADD_TO_BASKET_ACTION" => "ADD",
					"TOP_ELEMENT_COUNT" => "6",
					"TOP_ELEMENT_SORT_FIELD" => "sort",
					"TOP_ELEMENT_SORT_FIELD2" => "id",
					"TOP_ELEMENT_SORT_ORDER" => "asc",
					"TOP_ELEMENT_SORT_ORDER2" => "desc",
					"TOP_ENLARGE_PRODUCT" => "STRICT",
					"TOP_LINE_ELEMENT_COUNT" => "",
					"TOP_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
					"TOP_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
					"TOP_PROPERTY_CODE" => array(
						0 => "ATT_PARTNER",
						1 => "",
					),
					"TOP_PROPERTY_CODE_MOBILE" => "",
					"TOP_ROTATE_TIMER" => "30",
					"TOP_SHOW_SLIDER" => "Y",
					"TOP_SLIDER_INTERVAL" => "3000",
					"TOP_SLIDER_PROGRESS" => "N",
					"TOP_VIEW_MODE" => "SECTION",
					"USE_ALSO_BUY" => "N",
					"USE_BIG_DATA" => "Y",
					"USE_COMMON_SETTINGS_BASKET_POPUP" => "N",
					"USE_COMPARE" => "N",
					"USE_ELEMENT_COUNTER" => "Y",
					"USE_ENHANCED_ECOMMERCE" => "N",
					"USE_FILTER" => "N",
					"USE_GIFTS_DETAIL" => "N",
					"USE_GIFTS_MAIN_PR_SECTION_LIST" => "N",
					"USE_GIFTS_SECTION" => "N",
					"USE_MAIN_ELEMENT_SECTION" => "Y",
					"USE_PRICE_COUNT" => "N",
					"USE_PRODUCT_QUANTITY" => "Y",
					"USE_REVIEW" => "N",
					"USE_SALE_BESTSELLERS" => "N",
					"USE_STORE" => "N",
					"FILTER_NAME" => "",
					"FILTER_FIELD_CODE" => array(
						0 => "",
						1 => "",
					),
					"FILTER_PROPERTY_CODE" => array(
						0 => "",
						1 => "",
					),
					"FILTER_PRICE_CODE" => "",
					"SEF_URL_TEMPLATES" => array(
						"sections" => "",
						"section" => "#SECTION_CODE#/",
						"element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
						"compare" => "compare.php?action=#ACTION_CODE#",
						"smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/",
					),
					"VARIABLE_ALIASES" => array(
						"compare" => array(
							"ACTION_CODE" => "action",
						),
					)
				),
				false,
				array(
					"ACTIVE_COMPONENT" => "Y"
				)
			);?>
		</div>
	</div>
<?
require($_SERVER['DOCUMENT_ROOT'].'/bitrix/footer.php');
?>
